"""Daily digest -> reports/daily/YYYY-MM-DD.md.

One page. Numbers, not adjectives. If it takes longer than two minutes to read,
it has failed at its job.
"""

from __future__ import annotations

from datetime import date
from pathlib import Path

from . import kb
from .guardrails import SpendLedger

REPORTS = Path("reports/daily")


def build(day: date | None = None, ledger: SpendLedger | None = None,
          queue: list[str] | None = None, skeptic_kill_rate: float | None = None,
          infra_failure_rate: float | None = None, overhead_ratio: float | None = None,
          root: Path | str = REPORTS) -> Path:
    day = day or date.today()
    spend = (ledger or SpendLedger()).snapshot()
    findings = kb.load_all()
    today = [f for f in findings if str(f.get("created_utc", "")).startswith(day.isoformat())]

    def count(status: str) -> int:
        return sum(1 for f in today if f.get("status") == status)

    lines = [
        f"# LERM daily digest — {day.isoformat()}",
        "",
        "## Numbers",
        f"- experiments settled today: {len(today)}  "
        f"(SUPPORTED {count('SUPPORTED')} / REFUTED {count('REFUTED')} / UNCERTAIN {count('UNCERTAIN')})",
        f"- knowledge base total: {len(findings)} findings",
        f"- spend: ${spend['hour']:.2f}/h, ${spend['day']:.2f}/day, ${spend['week']:.2f}/week "
        f"(caps ${spend['caps']['usd_per_hour']:.0f}/${spend['caps']['usd_per_day']:.0f}/"
        f"${spend['caps']['usd_per_week']:.0f})",
    ]
    if skeptic_kill_rate is not None:
        warn = "  <-- AUDIT THE SKEPTIC" if skeptic_kill_rate < 0.05 else ""
        lines.append(f"- skeptic kill rate: {skeptic_kill_rate:.0%}{warn}")
    if infra_failure_rate is not None:
        warn = "  <-- exceeds 2% budget" if infra_failure_rate > 0.02 else ""
        lines.append(f"- infra-caused failures: {infra_failure_rate:.2%}{warn}")
    if overhead_ratio is not None:
        warn = "  <-- exceeds 10% budget" if overhead_ratio > 0.10 else ""
        lines.append(f"- median LERM overhead: {overhead_ratio:.1%}{warn}")

    lines += ["", "## Findings today"]
    if today:
        for f in today:
            es = f.get("effect_size", {})
            lines.append(
                f"- **{f['id']}** [{f['status']}] {f['hypothesis'][:90]} — "
                f"effect {es.get('value', 0):+.3f} "
                f"[{es.get('ci_low', 0):+.3f}, {es.get('ci_high', 0):+.3f}], "
                f"FAR {f.get('false_accept_rate', float('nan')):.3f}"
            )
    else:
        lines.append("- none settled")

    lines += ["", "## Killed by the skeptic"]
    kills = [f for f in today if f.get("status") == "REFUTED"]
    lines += [f"- {f['id']}: {(f.get('skeptic_attempts') or [{}])[0].get('detail', '')[:120]}"
              for f in kills] or ["- none"]

    lines += ["", "## Queue for tomorrow"]
    lines += [f"- {q}" for q in (queue or [])] or ["- idle: replicating prior findings"]
    lines += ["", "---", "_Generated by lerm.digest. Adjectives are a bug; report numbers._", ""]

    Path(root).mkdir(parents=True, exist_ok=True)
    out = Path(root) / f"{day.isoformat()}.md"
    out.write_text("\n".join(lines), encoding="utf-8")
    return out
